// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: gen.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Req1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field1 string `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
}

func (x *Req1) Reset() {
	*x = Req1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req1) ProtoMessage() {}

func (x *Req1) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req1.ProtoReflect.Descriptor instead.
func (*Req1) Descriptor() ([]byte, []int) {
	return file_gen_proto_rawDescGZIP(), []int{0}
}

func (x *Req1) GetField1() string {
	if x != nil {
		return x.Field1
	}
	return ""
}

type Resp1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field2 int64 `protobuf:"varint,1,opt,name=field2,proto3" json:"field2,omitempty"`
}

func (x *Resp1) Reset() {
	*x = Resp1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resp1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp1) ProtoMessage() {}

func (x *Resp1) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp1.ProtoReflect.Descriptor instead.
func (*Resp1) Descriptor() ([]byte, []int) {
	return file_gen_proto_rawDescGZIP(), []int{1}
}

func (x *Resp1) GetField2() int64 {
	if x != nil {
		return x.Field2
	}
	return 0
}

type Req2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field1 string `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
}

func (x *Req2) Reset() {
	*x = Req2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req2) ProtoMessage() {}

func (x *Req2) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req2.ProtoReflect.Descriptor instead.
func (*Req2) Descriptor() ([]byte, []int) {
	return file_gen_proto_rawDescGZIP(), []int{2}
}

func (x *Req2) GetField1() string {
	if x != nil {
		return x.Field1
	}
	return ""
}

type Resp2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field2 int64 `protobuf:"varint,1,opt,name=field2,proto3" json:"field2,omitempty"`
}

func (x *Resp2) Reset() {
	*x = Resp2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gen_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resp2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp2) ProtoMessage() {}

func (x *Resp2) ProtoReflect() protoreflect.Message {
	mi := &file_gen_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp2.ProtoReflect.Descriptor instead.
func (*Resp2) Descriptor() ([]byte, []int) {
	return file_gen_proto_rawDescGZIP(), []int{3}
}

func (x *Resp2) GetField2() int64 {
	if x != nil {
		return x.Field2
	}
	return 0
}

var File_gen_proto protoreflect.FileDescriptor

var file_gen_proto_rawDesc = []byte{
	0x0a, 0x09, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x04, 0x72,
	0x65, 0x71, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x22, 0x1f, 0x0a, 0x05, 0x72,
	0x65, 0x73, 0x70, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x22, 0x1e, 0x0a, 0x04,
	0x72, 0x65, 0x71, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x22, 0x1f, 0x0a, 0x05,
	0x72, 0x65, 0x73, 0x70, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x32, 0x33, 0x0a,
	0x06, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x31, 0x12, 0x13, 0x0a, 0x02, 0x48, 0x69, 0x12, 0x05, 0x2e,
	0x72, 0x65, 0x71, 0x31, 0x1a, 0x06, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x31, 0x12, 0x14, 0x0a, 0x03,
	0x48, 0x69, 0x32, 0x12, 0x05, 0x2e, 0x72, 0x65, 0x71, 0x32, 0x1a, 0x06, 0x2e, 0x72, 0x65, 0x73,
	0x70, 0x32, 0x32, 0x33, 0x0a, 0x06, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x32, 0x12, 0x13, 0x0a, 0x02,
	0x48, 0x69, 0x12, 0x05, 0x2e, 0x72, 0x65, 0x71, 0x31, 0x1a, 0x06, 0x2e, 0x72, 0x65, 0x73, 0x70,
	0x31, 0x12, 0x14, 0x0a, 0x03, 0x48, 0x69, 0x32, 0x12, 0x05, 0x2e, 0x72, 0x65, 0x71, 0x32, 0x1a,
	0x06, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x32, 0x42, 0x0a, 0x5a, 0x08, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x2f, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gen_proto_rawDescOnce sync.Once
	file_gen_proto_rawDescData = file_gen_proto_rawDesc
)

func file_gen_proto_rawDescGZIP() []byte {
	file_gen_proto_rawDescOnce.Do(func() {
		file_gen_proto_rawDescData = protoimpl.X.CompressGZIP(file_gen_proto_rawDescData)
	})
	return file_gen_proto_rawDescData
}

var file_gen_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gen_proto_goTypes = []interface{}{
	(*Req1)(nil),  // 0: req1
	(*Resp1)(nil), // 1: resp1
	(*Req2)(nil),  // 2: req2
	(*Resp2)(nil), // 3: resp2
}
var file_gen_proto_depIdxs = []int32{
	0, // 0: hello1.Hi:input_type -> req1
	2, // 1: hello1.Hi2:input_type -> req2
	0, // 2: hello2.Hi:input_type -> req1
	2, // 3: hello2.Hi2:input_type -> req2
	1, // 4: hello1.Hi:output_type -> resp1
	3, // 5: hello1.Hi2:output_type -> resp2
	1, // 6: hello2.Hi:output_type -> resp1
	3, // 7: hello2.Hi2:output_type -> resp2
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gen_proto_init() }
func file_gen_proto_init() {
	if File_gen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resp1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gen_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gen_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resp2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_gen_proto_goTypes,
		DependencyIndexes: file_gen_proto_depIdxs,
		MessageInfos:      file_gen_proto_msgTypes,
	}.Build()
	File_gen_proto = out.File
	file_gen_proto_rawDesc = nil
	file_gen_proto_goTypes = nil
	file_gen_proto_depIdxs = nil
}
